on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2.1
include:
  - board: nice_nano_v2
    shield: dactyl_cc_left
    snippet: zmk-usb-logging
