on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2.1

include:
  - board: nice_nano
    shield: dactyl_cc_left
    snippet: zmk-usb-logging  # <--- ADD THIS LINE HERE
  - board: nice_nano
    shield: dactyl_cc_right
  - board: nice_nano
    shield: settings_reset
